[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook_vault = "HaH6qJkNS6WkxjyjtKCNNRqLo6WLioubocXYXJjPCJ9Y"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
